#!/usr/bin/perl


open(WORDS, $ARGV[0]);
open(WORDS1, $ARGV[1]);

while (<WORDS>) {
    chomp; 
    $_=uc($_);
    $words{$_} = 1;
} 

while (<WORDS1>) {
    chomp;
    $_=uc($_);
    if ( $words{$_}) {
	    print "$_\n"
	}
} 

